/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoteLoginRouteImport } from './routes/vote-login'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoPosthogRouteImport } from './routes/demo/posthog'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiElectionVoteRouteImport } from './routes/api/election/vote'
import { Route as ApiElectionStopRouteImport } from './routes/api/election/stop'
import { Route as ApiElectionStateRouteImport } from './routes/api/election/state'
import { Route as ApiElectionStartRouteImport } from './routes/api/election/start'
import { Route as ApiElectionResultsRouteImport } from './routes/api/election/results'
import { Route as ApiElectionResetRouteImport } from './routes/api/election/reset'
import { Route as ApiElectionExportRouteImport } from './routes/api/election/export'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VoteLoginRoute = VoteLoginRouteImport.update({
  id: '/vote-login',
  path: '/vote-login',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPosthogRoute = DemoPosthogRouteImport.update({
  id: '/demo/posthog',
  path: '/demo/posthog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectionVoteRoute = ApiElectionVoteRouteImport.update({
  id: '/api/election/vote',
  path: '/api/election/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectionStopRoute = ApiElectionStopRouteImport.update({
  id: '/api/election/stop',
  path: '/api/election/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectionStateRoute = ApiElectionStateRouteImport.update({
  id: '/api/election/state',
  path: '/api/election/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectionStartRoute = ApiElectionStartRouteImport.update({
  id: '/api/election/start',
  path: '/api/election/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectionResultsRoute = ApiElectionResultsRouteImport.update({
  id: '/api/election/results',
  path: '/api/election/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectionResetRoute = ApiElectionResetRouteImport.update({
  id: '/api/election/reset',
  path: '/api/election/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectionExportRoute = ApiElectionExportRouteImport.update({
  id: '/api/election/export',
  path: '/api/election/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/results': typeof ResultsRoute
  '/vote': typeof VoteRoute
  '/vote-login': typeof VoteLoginRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/election/export': typeof ApiElectionExportRoute
  '/api/election/reset': typeof ApiElectionResetRoute
  '/api/election/results': typeof ApiElectionResultsRoute
  '/api/election/start': typeof ApiElectionStartRoute
  '/api/election/state': typeof ApiElectionStateRoute
  '/api/election/stop': typeof ApiElectionStopRoute
  '/api/election/vote': typeof ApiElectionVoteRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/results': typeof ResultsRoute
  '/vote': typeof VoteRoute
  '/vote-login': typeof VoteLoginRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/election/export': typeof ApiElectionExportRoute
  '/api/election/reset': typeof ApiElectionResetRoute
  '/api/election/results': typeof ApiElectionResultsRoute
  '/api/election/start': typeof ApiElectionStartRoute
  '/api/election/state': typeof ApiElectionStateRoute
  '/api/election/stop': typeof ApiElectionStopRoute
  '/api/election/vote': typeof ApiElectionVoteRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/results': typeof ResultsRoute
  '/vote': typeof VoteRoute
  '/vote-login': typeof VoteLoginRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/election/export': typeof ApiElectionExportRoute
  '/api/election/reset': typeof ApiElectionResetRoute
  '/api/election/results': typeof ApiElectionResultsRoute
  '/api/election/start': typeof ApiElectionStartRoute
  '/api/election/state': typeof ApiElectionStateRoute
  '/api/election/stop': typeof ApiElectionStopRoute
  '/api/election/vote': typeof ApiElectionVoteRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-dashboard'
    | '/results'
    | '/vote'
    | '/vote-login'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/neon'
    | '/demo/posthog'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/election/export'
    | '/api/election/reset'
    | '/api/election/results'
    | '/api/election/start'
    | '/api/election/state'
    | '/api/election/stop'
    | '/api/election/vote'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-dashboard'
    | '/results'
    | '/vote'
    | '/vote-login'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/neon'
    | '/demo/posthog'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/election/export'
    | '/api/election/reset'
    | '/api/election/results'
    | '/api/election/start'
    | '/api/election/state'
    | '/api/election/stop'
    | '/api/election/vote'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-dashboard'
    | '/results'
    | '/vote'
    | '/vote-login'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/neon'
    | '/demo/posthog'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/election/export'
    | '/api/election/reset'
    | '/api/election/results'
    | '/api/election/start'
    | '/api/election/state'
    | '/api/election/stop'
    | '/api/election/vote'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ResultsRoute: typeof ResultsRoute
  VoteRoute: typeof VoteRoute
  VoteLoginRoute: typeof VoteLoginRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoI18nRoute: typeof DemoI18nRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoPosthogRoute: typeof DemoPosthogRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiElectionExportRoute: typeof ApiElectionExportRoute
  ApiElectionResetRoute: typeof ApiElectionResetRoute
  ApiElectionResultsRoute: typeof ApiElectionResultsRoute
  ApiElectionStartRoute: typeof ApiElectionStartRoute
  ApiElectionStateRoute: typeof ApiElectionStateRoute
  ApiElectionStopRoute: typeof ApiElectionStopRoute
  ApiElectionVoteRoute: typeof ApiElectionVoteRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vote-login': {
      id: '/vote-login'
      path: '/vote-login'
      fullPath: '/vote-login'
      preLoaderRoute: typeof VoteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/posthog': {
      id: '/demo/posthog'
      path: '/demo/posthog'
      fullPath: '/demo/posthog'
      preLoaderRoute: typeof DemoPosthogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/election/vote': {
      id: '/api/election/vote'
      path: '/api/election/vote'
      fullPath: '/api/election/vote'
      preLoaderRoute: typeof ApiElectionVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/election/stop': {
      id: '/api/election/stop'
      path: '/api/election/stop'
      fullPath: '/api/election/stop'
      preLoaderRoute: typeof ApiElectionStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/election/state': {
      id: '/api/election/state'
      path: '/api/election/state'
      fullPath: '/api/election/state'
      preLoaderRoute: typeof ApiElectionStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/election/start': {
      id: '/api/election/start'
      path: '/api/election/start'
      fullPath: '/api/election/start'
      preLoaderRoute: typeof ApiElectionStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/election/results': {
      id: '/api/election/results'
      path: '/api/election/results'
      fullPath: '/api/election/results'
      preLoaderRoute: typeof ApiElectionResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/election/reset': {
      id: '/api/election/reset'
      path: '/api/election/reset'
      fullPath: '/api/election/reset'
      preLoaderRoute: typeof ApiElectionResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/election/export': {
      id: '/api/election/export'
      path: '/api/election/export'
      fullPath: '/api/election/export'
      preLoaderRoute: typeof ApiElectionExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ResultsRoute: ResultsRoute,
  VoteRoute: VoteRoute,
  VoteLoginRoute: VoteLoginRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoI18nRoute: DemoI18nRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoPosthogRoute: DemoPosthogRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiElectionExportRoute: ApiElectionExportRoute,
  ApiElectionResetRoute: ApiElectionResetRoute,
  ApiElectionResultsRoute: ApiElectionResultsRoute,
  ApiElectionStartRoute: ApiElectionStartRoute,
  ApiElectionStateRoute: ApiElectionStateRoute,
  ApiElectionStopRoute: ApiElectionStopRoute,
  ApiElectionVoteRoute: ApiElectionVoteRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
